ifeq ($(obj),)
obj := .
endif

DEPTH := ../../..

# Chip Support
AH_SUPPORT_AR5212?=1		# 5212 support
AH_SUPPORT_AR5416?=1		# 5416 support

include $(obj)/$(DEPTH)/linux/Makefile-linux.common

INCS += -I$(HAL) -I$(HAL)/$(OS) -I$(ATH) -I$(ATH_RATE) -I$(ATH_PKTLOG) -I$(WLAN) -I$(IF_WLAN) -I$(WLAN_TOP)/$(OS)/ath_hal

ifeq ($(strip $(AH_SUPPORT_AR5212)),1)
ath_rate_objs += ar5212Phy.o
endif

ifeq ($(strip $(AH_SUPPORT_AR5416)),1)
ath_rate_objs += ar5416Phy.o
endif


obj-m += ath_rate_atheros.o

EXTRA_CFLAGS+= $(INCS) $(COPTS)
ath_rate_atheros-objs := ratectrl.o ratectrl_11n.o ratectrl_11nViVo.o if_athrate.o $(ath_rate_objs)
