ifeq ($(obj),)
obj := .
endif

DEPTH := ../../..

include $(obj)/$(DEPTH)/linux/Makefile-linux.common

INCS += -I$(HAL) -I$(HAL)/$(OS) -I$(ATH) -I$(ATH_RATE) -I$(WLAN) -I$(IF_WLAN) -I$(ATH_DFS)

obj-m += ath_dfs.o

EXTRA_CFLAGS+= $(INCS) $(COPTS)

ath_dfs-objs := dfs.o
